---
# SonarMark Requirements
#
# Test Execution Strategy:
# This file links requirements to tests across multiple execution contexts:
# - Unit tests: Run locally via 'dotnet test' (validates most requirements)
# - Self-validation tests: Run via 'sonarmark --validate' in CI integration-test job
#   (validates SONAR-003, SONAR-004, SONAR-005, RPT-001, VAL-001)
# - Platform tests: Run across OS/runtime matrix in CI integration-test job
#   (validates PLT-001 through PLT-005)
#
# Note: Running 'dotnet reqstream --enforce' locally will show some unsatisfied requirements.
# This is expected - full validation requires the complete CI pipeline.
sections:
  - title: SonarMark Requirements
    sections:
      - title: Command-Line Interface
        requirements:
          - id: CLI-001
            title: The tool shall provide a command-line interface.
            justification: |
              A command-line interface is essential for automation and integration into CI/CD pipelines.
              It allows users to incorporate SonarMark into their build processes without manual interaction,
              enabling automated quality checks and reporting as part of the development workflow.
            tests:
              - IntegrationTest_VersionFlag_OutputsVersion
              - IntegrationTest_HelpFlag_OutputsUsageInformation

          - id: CLI-002
            title: The tool shall display version information when requested.
            justification: |
              Version information helps users verify which version of the tool they are running, which is
              critical for troubleshooting, ensuring compatibility, and tracking which features are available.
              This is a standard expectation for command-line tools.
            tests:
              - IntegrationTest_VersionFlag_OutputsVersion

          - id: CLI-003
            title: The tool shall display help information when requested.
            justification: |
              Help information provides users with usage instructions and available options without needing
              to consult external documentation. This improves usability and reduces the learning curve,
              especially for new users or those who need a quick reference.
            tests:
              - IntegrationTest_HelpFlag_OutputsUsageInformation

          - id: CLI-004
            title: The tool shall support silent mode to suppress console output.
            justification: |
              Silent mode is important for automated environments where console output may interfere with
              log parsing or where minimal output is preferred. It allows the tool to run without cluttering
              build logs while still performing its analysis and reporting functions.
            tests:
              - IntegrationTest_SilentFlag_SuppressesOutput

          - id: CLI-005
            title: The tool shall support writing output to a log file.
            justification: |
              Log file output enables persistent recording of tool execution for later review and audit trails.
              This is particularly valuable for debugging issues, maintaining compliance records, and analyzing
              trends in code quality over time without relying on transient console output.
            tests:
              - Context_Create_WithLogFile_WritesToLogFile

          - id: CLI-006
            title: The tool shall support enforcing quality gate checks.
            justification: |
              Quality gate enforcement allows the tool to fail builds when quality standards are not met,
              preventing low-quality code from progressing through the pipeline. This is a critical feature
              for maintaining code quality standards and preventing technical debt accumulation.
            tests:
              - IntegrationTest_EnforceFlag_IsAccepted

      - title: SonarQube/SonarCloud Integration
        requirements:
          - id: SONAR-001
            title: The tool shall connect to SonarQube/SonarCloud servers.
            justification: |
              Connection to SonarQube/SonarCloud servers is the core functionality of the tool, enabling
              retrieval of code quality metrics, analysis results, and quality gate status. Without this
              capability, the tool cannot fulfill its primary purpose of integrating Sonar analysis into
              development workflows.
            tests:
              - IntegrationTest_MissingServerParameter_ShowsError

          - id: SONAR-002
            title: The tool shall authenticate with SonarQube/SonarCloud using tokens.
            justification: |
              Token-based authentication is the secure and recommended method for accessing SonarQube/SonarCloud
              APIs. It provides better security than password-based authentication and is essential for
              automated environments where interactive authentication is not possible.
            tests:
              - IntegrationTest_TokenParameter_IsAccepted

          - id: SONAR-003
            title: The tool shall fetch quality gate status from SonarQube/SonarCloud.
            justification: |
              Quality gate status indicates whether code meets the defined quality standards and is fundamental
              to the tool's enforcement capabilities. This information is essential for making pass/fail
              decisions in CI/CD pipelines and providing visibility into overall code quality.
            tests:
              - SonarMark_QualityGateRetrieval

          - id: SONAR-004
            title: The tool shall fetch issues from SonarQube/SonarCloud.
            justification: |
              Issues represent code quality problems identified by Sonar analysis. Fetching and reporting
              these issues allows developers to understand what needs to be fixed and provides the detailed
              information needed to improve code quality beyond just pass/fail status.
            tests:
              - SonarMark_IssuesRetrieval

          - id: SONAR-005
            title: The tool shall fetch security hot-spots from SonarQube/SonarCloud.
            justification: |
              Security hot-spots highlight code that requires security review, helping teams identify and
              address potential security vulnerabilities. This is critical for maintaining secure applications
              and meeting security compliance requirements.
            tests:
              - SonarMark_HotSpotsRetrieval

          - id: SONAR-006
            title: The tool shall support filtering by project key.
            justification: |
              Project key filtering is essential for identifying which specific project to analyze when
              multiple projects exist on a Sonar server. This parameter is mandatory for the tool to
              retrieve the correct analysis results for the intended codebase.
            tests:
              - IntegrationTest_MissingProjectKeyParameter_ShowsError

          - id: SONAR-007
            title: The tool shall support filtering by branch.
            justification: |
              Branch filtering enables analysis of specific branches in version control, which is crucial
              for multi-branch development workflows. This allows teams to check quality gates for feature
              branches, pull requests, and release branches independently.
            tests:
              - IntegrationTest_BranchParameter_IsAccepted

      - title: Report Generation
        requirements:
          - id: RPT-001
            title: The tool shall generate markdown reports.
            justification: |
              Markdown reports provide human-readable documentation of code quality that can be easily
              integrated into documentation systems, pull request comments, and version control. Markdown
              is widely supported and readable both as plain text and rendered, making it ideal for
              developer communication and documentation.
            tests:
              - IntegrationTest_ReportParameter_IsAccepted
              - SonarMark_MarkdownReportGeneration

          - id: RPT-002
            title: The tool shall support configurable report depth.
            justification: |
              Configurable report depth allows users to control the level of detail in generated reports,
              accommodating different use cases from high-level summaries to detailed analysis. This
              flexibility ensures reports can be integrated into various document structures without
              conflicting heading levels.
            tests:
              - IntegrationTest_ReportDepthWithZero_ShowsError
              - IntegrationTest_ReportDepthWithInvalidValue_ShowsError
              - IntegrationTest_ReportDepthWithoutValue_ShowsError

          - id: RPT-003
            title: The tool shall include quality gate status in reports.
            justification: |
              Quality gate status is the most important metric in the report, providing a clear pass/fail
              indication of code quality. Including this information with condition details helps teams
              understand whether their code meets quality standards and which metrics need improvement.
            tests:
              - SonarQualityResult_ToMarkdown_Depth1_ProducesCorrectOutput
              - SonarQualityResult_ToMarkdown_Depth3_UsesCorrectHeadingLevels
              - SonarQualityResult_ToMarkdown_Depth6_ProducesCorrectOutput
              - SonarQualityResult_ToMarkdown_NoConditions_ExcludesConditionsSection
              - SonarQualityResult_ToMarkdown_WarnStatus_ProducesCorrectOutput
              - SonarQualityResult_ToMarkdown_WithFriendlyNames_UsesFriendlyNames

          - id: RPT-004
            title: The tool shall categorize and report issues by type and severity.
            justification: |
              Categorizing issues by type and severity helps teams prioritize remediation efforts and
              understand the nature of quality problems in their codebase. This organization makes it
              easier to address the most critical issues first and track specific categories of problems.
            tests:
              - SonarQualityResult_ToMarkdown_WithIssues_ProducesCompilerStyleOutput
              - SonarQualityResult_ToMarkdown_WithSingularCounts_ShowsCorrectText

          - id: RPT-005
            title: The tool shall report security hot-spots requiring review.
            justification: |
              Security hot-spots require manual review to determine if they represent actual vulnerabilities.
              Reporting these separately from standard issues ensures they receive appropriate security-focused
              attention and helps teams maintain secure coding practices.
            tests:
              - SonarQualityResult_ToMarkdown_WithHotSpots_ProducesCompilerStyleOutput

      - title: Validation and Testing
        requirements:
          - id: VAL-001
            title: The tool shall support self-validation mode.
            justification: |
              Self-validation mode allows the tool to verify its own functionality without requiring
              external dependencies or a live Sonar server. This capability is essential for testing
              the tool itself and providing confidence in its operation before using it in production
              pipelines.
            tests:
              - IntegrationTest_ValidateFlag_OutputsNotImplemented
              - SonarMark_QualityGateRetrieval
              - SonarMark_IssuesRetrieval
              - SonarMark_HotSpotsRetrieval
              - SonarMark_MarkdownReportGeneration

          - id: VAL-002
            title: The tool shall write validation results to test result files.
            justification: |
              Writing validation results to test result files allows integration with standard testing
              frameworks and CI/CD tools. This enables validation outcomes to be tracked, reported, and
              integrated into build pipelines alongside other test results.
            tests:
              - Context_Create_ResultsFile_SetsResultsProperty
              - Context_Create_MissingResultsFilename_ThrowsException

          - id: VAL-003
            title: The tool shall support TRX format for test results.
            justification: |
              TRX (Test Results XML) is the native test results format for Microsoft testing tools and
              Visual Studio. Supporting this format ensures compatibility with .NET development workflows
              and enables seamless integration with Azure DevOps and other Microsoft-based CI/CD systems.
            tests:
              - Context_Create_ResultsFile_SetsResultsProperty

          - id: VAL-004
            title: The tool shall support JUnit format for test results.
            justification: |
              JUnit format is a widely-supported standard for test results across many platforms and tools,
              including Jenkins, GitLab CI, and GitHub Actions. Supporting this format ensures broad
              compatibility with diverse CI/CD environments beyond Microsoft ecosystems.
            tests:
              - Context_Create_ResultsFile_SetsResultsProperty

      - title: Quality Enforcement
        requirements:
          - id: ENF-001
            title: The tool shall support enforcement mode to fail on quality gate failures.
            justification: |
              Enforcement mode is critical for maintaining code quality standards by preventing builds
              from succeeding when quality gates fail. This capability enables teams to establish and
              maintain quality policies that must be met before code can be merged or deployed.
            tests:
              - Context_Create_EnforceFlag_SetsEnforceProperty

          - id: ENF-002
            title: The tool shall return non-zero exit code when quality gate fails in enforcement mode.
            justification: |
              Returning a non-zero exit code on quality gate failure is the standard mechanism for
              indicating failure in command-line tools and CI/CD systems. This allows build systems
              to automatically detect and halt builds when quality standards are not met.
            tests:
              - IntegrationTest_EnforceFlag_IsAccepted

      - title: Platform Support
        requirements:
          - id: PLT-001
            title: The tool shall run on Windows operating systems.
            justification: |
              Windows is a major development platform, especially for .NET development. Supporting Windows
              ensures the tool can be used in Windows-based development environments and CI/CD systems,
              which are common in enterprise .NET development shops.
            # Test source pattern "windows@" ensures these tests ran on Windows.
            # This filtering is necessary to prove Windows OS functionality.
            tests:
              - windows@IntegrationTest_VersionFlag_OutputsVersion
              - windows@IntegrationTest_HelpFlag_OutputsUsageInformation
              - windows@IntegrationTest_ReportParameter_IsAccepted
              - windows@SonarMark_QualityGateRetrieval
              - windows@SonarMark_IssuesRetrieval
              - windows@SonarMark_HotSpotsRetrieval
              - windows@SonarMark_MarkdownReportGeneration

          - id: PLT-002
            title: The tool shall run on Linux operating systems.
            justification: |
              Linux is the dominant platform for cloud-based CI/CD systems and containerized environments.
              Supporting Linux ensures the tool can be used in modern DevOps pipelines, Docker containers,
              and popular CI platforms like GitHub Actions, GitLab CI, and Jenkins.
            # Test source pattern "ubuntu@" ensures these tests ran on Linux.
            # This filtering is necessary to prove Linux OS functionality.
            tests:
              - ubuntu@IntegrationTest_VersionFlag_OutputsVersion
              - ubuntu@IntegrationTest_HelpFlag_OutputsUsageInformation
              - ubuntu@IntegrationTest_ReportParameter_IsAccepted
              - ubuntu@SonarMark_QualityGateRetrieval
              - ubuntu@SonarMark_IssuesRetrieval
              - ubuntu@SonarMark_HotSpotsRetrieval
              - ubuntu@SonarMark_MarkdownReportGeneration

          - id: PLT-003
            title: The tool shall support .NET 8.0 runtime.
            justification: |
              .NET 8.0 is a Long-Term Support (LTS) release with support until November 2026. Supporting
              this version ensures compatibility with enterprise environments that standardize on LTS
              releases for stability and long-term support guarantees.
            # Test source pattern "dotnet8.x@" ensures these tests ran on .NET 8.0.
            # This filtering is necessary to prove .NET 8.0 runtime support.
            tests:
              - dotnet8.x@SonarMark_QualityGateRetrieval
              - dotnet8.x@SonarMark_IssuesRetrieval
              - dotnet8.x@SonarMark_HotSpotsRetrieval
              - dotnet8.x@SonarMark_MarkdownReportGeneration

          - id: PLT-004
            title: The tool shall support .NET 9.0 runtime.
            justification: |
              .NET 9.0 is a Standard Term Support (STS) release providing access to the latest features
              and performance improvements. Supporting this version allows users who adopt newer .NET
              versions to use the tool without compatibility concerns.
            # Test source pattern "dotnet9.x@" ensures these tests ran on .NET 9.0.
            # This filtering is necessary to prove .NET 9.0 runtime support.
            tests:
              - dotnet9.x@SonarMark_QualityGateRetrieval
              - dotnet9.x@SonarMark_IssuesRetrieval
              - dotnet9.x@SonarMark_HotSpotsRetrieval
              - dotnet9.x@SonarMark_MarkdownReportGeneration

          - id: PLT-005
            title: The tool shall support .NET 10.0 runtime.
            justification: |
              .NET 10.0 is the next Long-Term Support (LTS) release scheduled for November 2025. Supporting
              this version ensures the tool remains compatible with the latest LTS release, providing users
              with a future-proof solution and access to the newest platform capabilities.
            # Test source pattern "dotnet10.x@" ensures these tests ran on .NET 10.0.
            # This filtering is necessary to prove .NET 10.0 runtime support.
            tests:
              - dotnet10.x@SonarMark_QualityGateRetrieval
              - dotnet10.x@SonarMark_IssuesRetrieval
              - dotnet10.x@SonarMark_HotSpotsRetrieval
              - dotnet10.x@SonarMark_MarkdownReportGeneration
