---
sections:
  - title: "SonarMark Requirements"
    sections:
      - title: "Command-Line Interface"
        requirements:
          - id: "CLI-001"
            title: "The tool shall provide a command-line interface."
            tests:
              - "Context_Create_NoArguments_ReturnsDefaultContext"
              - "Context_Create_UnsupportedArgument_ThrowsException"

          - id: "CLI-002"
            title: "The tool shall display version information when requested."
            tests:
              - "Program_Version_NotEmpty_IsNotEmpty"
              - "Program_Run_VersionFlag_OutputsVersion"
              - "Context_Create_VersionFlag_SetsVersionProperty"
              - "IntegrationTest_VersionFlag_OutputsVersion"

          - id: "CLI-003"
            title: "The tool shall display help information when requested."
            tests:
              - "Program_Run_HelpFlag_OutputsBannerAndHelp"
              - "Context_Create_HelpFlags_SetsHelpProperty"
              - "IntegrationTest_HelpFlag_OutputsHelp"

          - id: "CLI-004"
            title: "The tool shall support silent mode to suppress console output."
            tests:
              - "Context_Create_SilentFlag_SetsSilentProperty"
              - "Context_WriteLine_SilentMode_DoesNotWriteToConsole"
              - "Context_WriteError_SilentMode_DoesNotWriteToConsole"

          - id: "CLI-005"
            title: "The tool shall support writing output to a log file."
            tests:
              - "Context_Create_WithLogFile_WritesToLogFile"
              - "Context_Create_MissingLogFilename_ThrowsException"
              - "Context_Create_InvalidLogFilePath_ThrowsException"

      - title: "SonarQube/SonarCloud Integration"
        requirements:
          - id: "SONAR-001"
            title: "The tool shall connect to SonarQube/SonarCloud servers."
            tests:
              - "Context_Create_Server_SetsServerProperty"
              - "Context_Create_MissingServer_ThrowsException"
              - "Program_Run_NoFlags_OutputsBannerAndRequiresServer"

          - id: "SONAR-002"
            title: "The tool shall authenticate with SonarQube/SonarCloud using tokens."
            tests:
              - "Context_Create_Token_SetsTokenProperty"
              - "Context_Create_MissingToken_ThrowsException"

          - id: "SONAR-003"
            title: "The tool shall fetch quality gate status from SonarQube/SonarCloud."
            tests:
              - "SonarQubeClient_FetchQualityGateAsync_ValidResponse_ReturnsQualityGate"
              - "SonarQubeClient_FetchQualityGateAsync_EmptyResponse_ReturnsNull"
              - "SonarQubeClient_FetchQualityGateAsync_ErrorResponse_ReturnsNull"
              - "SonarQubeClient_FetchQualityGateAsync_NetworkError_ReturnsNull"

          - id: "SONAR-004"
            title: "The tool shall fetch issues from SonarQube/SonarCloud."
            tests:
              - "SonarQubeClient_FetchIssuesAsync_ValidResponse_ReturnsIssues"
              - "SonarQubeClient_FetchIssuesAsync_EmptyResponse_ReturnsEmptyList"
              - "SonarQubeClient_FetchIssuesAsync_ErrorResponse_ReturnsEmptyList"
              - "SonarQubeClient_FetchIssuesAsync_NetworkError_ReturnsEmptyList"
              - "SonarQubeClient_FetchIssuesAsync_MultiplePages_ReturnsAllIssues"

          - id: "SONAR-005"
            title: "The tool shall fetch security hot-spots from SonarQube/SonarCloud."
            tests:
              - "SonarQubeClient_FetchHotSpotsAsync_ValidResponse_ReturnsHotSpots"
              - "SonarQubeClient_FetchHotSpotsAsync_EmptyResponse_ReturnsEmptyList"
              - "SonarQubeClient_FetchHotSpotsAsync_ErrorResponse_ReturnsEmptyList"
              - "SonarQubeClient_FetchHotSpotsAsync_NetworkError_ReturnsEmptyList"
              - "SonarQubeClient_FetchHotSpotsAsync_MultiplePages_ReturnsAllHotSpots"

          - id: "SONAR-006"
            title: "The tool shall support filtering by project key."
            tests:
              - "Context_Create_ProjectKey_SetsProjectKeyProperty"
              - "Context_Create_MissingProjectKey_ThrowsException"

          - id: "SONAR-007"
            title: "The tool shall support filtering by branch."
            tests:
              - "Context_Create_Branch_SetsBranchProperty"
              - "Context_Create_MissingBranch_ThrowsException"

      - title: "Report Generation"
        requirements:
          - id: "RPT-001"
            title: "The tool shall generate markdown reports."
            tests:
              - "Context_Create_ReportFile_SetsReportProperty"
              - "Context_Create_MissingReportFilename_ThrowsException"
              - "Program_Run_WithReportFile_GeneratesReport"
              - "IntegrationTest_ReportGeneration_CreatesMarkdownFile"

          - id: "RPT-002"
            title: "The tool shall support configurable report depth."
            tests:
              - "Context_Create_ReportDepth_SetsReportDepthProperty"
              - "Context_Create_MissingReportDepth_ThrowsException"
              - "Context_Create_InvalidReportDepth_ThrowsException"

          - id: "RPT-003"
            title: "The tool shall include quality gate status in reports."
            tests:
              - "SonarQualityResult_ToString_WithConditions_FormatsCorrectly"
              - "SonarQualityResult_ToString_WithoutConditions_FormatsCorrectly"

          - id: "RPT-004"
            title: "The tool shall categorize and report issues by type and severity."
            tests:
              - "SonarIssue_ToString_WithAllFields_FormatsCorrectly"
              - "SonarIssue_ToString_WithMinimalFields_FormatsCorrectly"
              - "SonarIssue_IssueType_ValidType_ReturnsType"
              - "SonarIssue_IssueType_InvalidType_ReturnsUnknown"
              - "SonarIssue_IssueSeverity_ValidSeverity_ReturnsSeverity"
              - "SonarIssue_IssueSeverity_InvalidSeverity_ReturnsUnknown"

          - id: "RPT-005"
            title: "The tool shall report security hot-spots requiring review."
            tests:
              - "SonarHotSpot_ToString_WithAllFields_FormatsCorrectly"
              - "SonarHotSpot_ToString_WithMinimalFields_FormatsCorrectly"

      - title: "Validation and Testing"
        requirements:
          - id: "VAL-001"
            title: "The tool shall support self-validation mode."
            tests:
              - "Program_Run_ValidateFlag_OutputsNotImplemented"
              - "Context_Create_ValidateFlag_SetsValidateProperty"

          - id: "VAL-002"
            title: "The tool shall write validation results to test result files."
            tests:
              - "Context_Create_ResultsFile_SetsResultsProperty"
              - "Context_Create_MissingResultsFilename_ThrowsException"
              - "Validation_WriteResults_WithTrxExtension_CreatesTrxFile"
              - "Validation_WriteResults_WithXmlExtension_CreatesJUnitFile"

          - id: "VAL-003"
            title: "The tool shall support TRX format for test results."
            tests:
              - "Validation_WriteResults_WithTrxExtension_CreatesTrxFile"

          - id: "VAL-004"
            title: "The tool shall support JUnit format for test results."
            tests:
              - "Validation_WriteResults_WithXmlExtension_CreatesJUnitFile"

      - title: "Quality Enforcement"
        requirements:
          - id: "ENF-001"
            title: "The tool shall support enforcement mode to fail on quality gate failures."
            tests:
              - "Context_Create_EnforceFlag_SetsEnforceProperty"

          - id: "ENF-002"
            title: "The tool shall return non-zero exit code when quality gate fails in enforcement mode."
            tests:
              - "Program_Run_WithFailedQualityGateAndEnforce_ReturnsNonZero"

      - title: "Platform Support"
        requirements:
          - id: "PLT-001"
            title: "The tool shall run on Windows operating systems."
            tests:
              - "windows-latest@Program_Version_NotEmpty_IsNotEmpty"
              - "windows-latest@IntegrationTest_VersionFlag_OutputsVersion"
              - "windows-latest@IntegrationTest_HelpFlag_OutputsHelp"
              - "windows-latest@IntegrationTest_ReportGeneration_CreatesMarkdownFile"

          - id: "PLT-002"
            title: "The tool shall run on Linux operating systems."
            tests:
              - "ubuntu-latest@Program_Version_NotEmpty_IsNotEmpty"
              - "ubuntu-latest@IntegrationTest_VersionFlag_OutputsVersion"
              - "ubuntu-latest@IntegrationTest_HelpFlag_OutputsHelp"
              - "ubuntu-latest@IntegrationTest_ReportGeneration_CreatesMarkdownFile"

          - id: "PLT-003"
            title: "The tool shall support .NET 8.0 runtime."
            tests:
              - "dotnet8.x@IntegrationTest_VersionFlag_OutputsVersion"
              - "dotnet8.x@IntegrationTest_HelpFlag_OutputsHelp"
              - "dotnet8.x@IntegrationTest_ReportGeneration_CreatesMarkdownFile"

          - id: "PLT-004"
            title: "The tool shall support .NET 9.0 runtime."
            tests:
              - "dotnet9.x@IntegrationTest_VersionFlag_OutputsVersion"
              - "dotnet9.x@IntegrationTest_HelpFlag_OutputsHelp"
              - "dotnet9.x@IntegrationTest_ReportGeneration_CreatesMarkdownFile"

          - id: "PLT-005"
            title: "The tool shall support .NET 10.0 runtime."
            tests:
              - "dotnet10.x@IntegrationTest_VersionFlag_OutputsVersion"
              - "dotnet10.x@IntegrationTest_HelpFlag_OutputsHelp"
              - "dotnet10.x@IntegrationTest_ReportGeneration_CreatesMarkdownFile"
