package OtsDependencies {
    doc /* Off-the-shelf (OTS) dependencies used by SonarMark. */

    part def TestResults {
        doc /* OTS: DemaConsulting.TestResults. */

        comment designRef /* Design: docs/design/ots/test-results.md */
        comment verificationRef /* Verification: docs/verification/ots/test-results.md */
        comment reqRef /* Requirements: docs/reqstream/ots/test-results.yaml */
    }
}
