package SonarMark {
    part def SonarIssue {
        doc /* Data record representing a SonarQube issue. */

        comment sourceRef /* Source: src/DemaConsulting.SonarMark/SonarIntegration/SonarIssue.cs */
        comment testRef /* Test: test/DemaConsulting.SonarMark.Tests/SonarIntegration/SonarIssueTests.cs */
        comment designRef /* Design: docs/design/sonar-mark/sonar-integration/sonar-issue.md */
        comment verificationRef /* Verification: docs/verification/sonar-mark/sonar-integration/sonar-issue.md */
        comment reqRef /* Requirements: docs/reqstream/sonar-mark/sonar-integration/sonar-issue.yaml */
    }
}
