package SonarMark {
    part def SonarHotSpot {
        doc /* Data record representing a SonarQube security hot-spot. */

        comment sourceRef /* Source: src/DemaConsulting.SonarMark/SonarIntegration/SonarHotSpot.cs */
        comment testRef /* Test: test/DemaConsulting.SonarMark.Tests/SonarIntegration/SonarHotSpotTests.cs */
        comment designRef /* Design: docs/design/sonar-mark/sonar-integration/sonar-hot-spot.md */
        comment verificationRef /* Verification: docs/verification/sonar-mark/sonar-integration/sonar-hot-spot.md */
        comment reqRef /* Requirements: docs/reqstream/sonar-mark/sonar-integration/sonar-hot-spot.yaml */
    }
}
